# Generated by Django 4.2 on 2023-06-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_alter_profile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='id',
            new_name='aid',
        ),
    ]
