# Generated by Django 4.2 on 2023-06-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_rename_id_stock_aid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='aid',
            new_name='id',
        ),
    ]
